<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0f34668ae1c7369d65a5697b02fc7065
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Academia\\App\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Academia\\App\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/wp-conten/themes/academia/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0f34668ae1c7369d65a5697b02fc7065::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0f34668ae1c7369d65a5697b02fc7065::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0f34668ae1c7369d65a5697b02fc7065::$classMap;

        }, null, ClassLoader::class);
    }
}
