<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'Academia\\App\\' => array($baseDir . '/wp-conten/themes/academia/src'),
);
